version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "3002:3000"
      - "3003:3002"
    volumes:
      - ./tarjetones/tcrisis-newsletter/:/app # aqui va al carpeta del proyecto que se desea ejecutar
      - /app/node_modules
    restart: unless-stopped
    networks:
      - tarjetones-net

volumes:
  tarjetones-volume:
    driver: local

networks:
  tarjetones-net:
      driver: bridge
  shared-sg-network:
    external: true
